// <auto-generated />
using System;
using JobForStudents.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobForStudents.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621165928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobForStudents.Models.BusinessProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanySize")
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("TaxCode")
                        .HasColumnType("text");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("BusinessProfiles");

                    b.HasData(
                        new
                        {
                            UserId = 3,
                            CompanyName = "Công ty TNHH Giải pháp Công nghệ J4S",
                            Industry = "Công nghệ thông tin",
                            IsVerified = true
                        },
                        new
                        {
                            UserId = 4,
                            CompanyName = "Studio Sáng tạo Hải Đăng",
                            Industry = "Truyền thông & Quảng cáo",
                            IsVerified = true
                        });
                });

            modelBuilder.Entity("JobForStudents.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CredentialUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("JobForStudents.Models.JobBid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedDays")
                        .HasColumnType("integer");

                    b.Property<int>("JobPostId")
                        .HasColumnType("integer");

                    b.Property<string>("Proposal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobPostId");

                    b.HasIndex("StudentId");

                    b.ToTable("JobBids");
                });

            modelBuilder.Entity("JobForStudents.Models.JobContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliverableContent")
                        .HasColumnType("text");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("JobPostId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("JobPostId");

                    b.HasIndex("StudentId");

                    b.ToTable("JobContracts");
                });

            modelBuilder.Entity("JobForStudents.Models.JobPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefits")
                        .HasColumnType("text");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<string>("BudgetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExperienceLevelRequired")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("JobPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Benefits = "Hỗ trợ tài liệu thực tập, có cơ hội làm việc chính thức sau khi tốt nghiệp.",
                            Budget = 3500000m,
                            BudgetType = "Fixed",
                            BusinessId = 3,
                            CreatedAt = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cần một bạn sinh viên thiết kế và lập trình website giới thiệu sản phẩm doanh nghiệp bằng ASP.NET Core MVC. Yêu cầu giao diện thân thiện, chuẩn SEO.",
                            ExperienceLevelRequired = "No_Experience",
                            IsDeleted = false,
                            Location = "Hà Nội (Hybrid)",
                            Quantity = 1,
                            Requirements = "Biết ASP.NET Core, HTML/CSS, SQL Server/PostgreSQL. Chủ động trong công việc.",
                            Status = "Open",
                            Title = "Lập trình website giới thiệu sản phẩm bằng ASP.NET Core",
                            UpdatedAt = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Benefits = "Thưởng thêm nếu hoàn thành xuất sắc và đúng hạn.",
                            Budget = 1500000m,
                            BudgetType = "Fixed",
                            BusinessId = 4,
                            CreatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cần thiết kế logo và 5 banner quảng cáo Facebook cho cửa hàng quần áo thời trang sinh viên.",
                            ExperienceLevelRequired = "Mid_Level",
                            IsDeleted = false,
                            Location = "Online",
                            Quantity = 1,
                            Requirements = "Thành thạo Photoshop, Illustrator. Gửi portfolio đính kèm.",
                            Status = "Open",
                            Title = "Thiết kế bộ nhận diện thương hiệu logo & banner",
                            UpdatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Benefits = "Môi trường học hỏi năng động, trả nhuận bút theo bài.",
                            Budget = 100000m,
                            BudgetType = "Hourly",
                            BusinessId = 3,
                            CreatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Viết 10 bài viết chuẩn SEO độ dài từ 1000-1500 từ về các chủ đề: Cloud VPS, hosting, máy chủ ảo, lập trình web.",
                            ExperienceLevelRequired = "No_Experience",
                            IsDeleted = false,
                            Location = "Online",
                            Quantity = 2,
                            Requirements = "Khả năng viết tốt, chuẩn SEO. Không sao chép, sử dụng AI hợp lý.",
                            Status = "Open",
                            Title = "Viết bài chuẩn SEO ngành Công nghệ, Hosting",
                            UpdatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Benefits = "Cung cấp mẫu thử sản phẩm miễn phí.",
                            Budget = 800000m,
                            BudgetType = "Fixed",
                            BusinessId = 4,
                            CreatedAt = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cần edit 5 video Tiktok ngắn dài khoảng 30s-60s từ tư liệu thô có sẵn. Chủ đề review phụ kiện điện thoại.",
                            ExperienceLevelRequired = "No_Experience",
                            IsDeleted = false,
                            Location = "Online",
                            Quantity = 1,
                            Requirements = "Sử dụng tốt CapCut hoặc Premiere Pro. Bắt trend nhạc tốt.",
                            Status = "Open",
                            Title = "Edit video Tiktok ngắn dạng review sản phẩm",
                            UpdatedAt = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("JobForStudents.Models.JobPostSkill", b =>
                {
                    b.Property<int>("JobPostId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("JobPostId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobPostSkills");

                    b.HasData(
                        new
                        {
                            JobPostId = 1,
                            SkillId = 10
                        },
                        new
                        {
                            JobPostId = 1,
                            SkillId = 9
                        },
                        new
                        {
                            JobPostId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            JobPostId = 2,
                            SkillId = 1
                        },
                        new
                        {
                            JobPostId = 3,
                            SkillId = 7
                        },
                        new
                        {
                            JobPostId = 3,
                            SkillId = 8
                        },
                        new
                        {
                            JobPostId = 4,
                            SkillId = 11
                        },
                        new
                        {
                            JobPostId = 4,
                            SkillId = 12
                        });
                });

            modelBuilder.Entity("JobForStudents.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("JobForStudents.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("JobForStudents.Models.PortfolioProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectUrl")
                        .HasColumnType("text");

                    b.Property<string>("RoleInProject")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("PortfolioProjects");
                });

            modelBuilder.Entity("JobForStudents.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentReviewId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ParentReviewId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("JobForStudents.Models.SavedJob", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("JobPostId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StudentId", "JobPostId");

                    b.HasIndex("JobPostId");

                    b.ToTable("SavedJobs");
                });

            modelBuilder.Entity("JobForStudents.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Thiết kế",
                            Name = "Thiết kế Banner"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Thiết kế",
                            Name = "Thiết kế Logo"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Dịch thuật",
                            Name = "Dịch thuật Anh-Việt"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Dịch thuật",
                            Name = "Dịch thuật Trung-Việt"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Làm slide",
                            Name = "Thiết kế slide PowerPoint"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Làm slide",
                            Name = "Làm slide báo cáo"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Viết content",
                            Name = "Viết bài chuẩn SEO"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Viết content",
                            Name = "Viết content Fanpage"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Code web",
                            Name = "Lập trình React/Vue"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Code web",
                            Name = "Lập trình ASP.NET Core"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Edit video",
                            Name = "Edit Video CapCut"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Edit video",
                            Name = "Edit Video Tiktok"
                        });
                });

            modelBuilder.Entity("JobForStudents.Models.StudentProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("GPA")
                        .HasColumnType("double precision");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Major")
                        .HasColumnType("text");

                    b.Property<string>("University")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Bio = "Sinh viên chuyên ngành CNTT trường Đại học Bách Khoa, có kinh nghiệm lập trình React, ASP.NET Core.",
                            DateOfBirth = new DateTime(2004, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Trần Minh Quang",
                            GPA = 3.6000000000000001,
                            Gender = "Nam",
                            GraduationYear = 2027,
                            Major = "Công nghệ thông tin",
                            University = "Đại học Bách Khoa Hà Nội"
                        },
                        new
                        {
                            UserId = 2,
                            Bio = "Sinh viên Thiết kế đồ họa trường Đại học Mỹ thuật Công nghiệp. Đam mê thiết kế logo, banner, giao diện người dùng UI/UX.",
                            DateOfBirth = new DateTime(2003, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Nguyễn Thảo Linh",
                            GPA = 3.7999999999999998,
                            Gender = "Nữ",
                            GraduationYear = 2026,
                            Major = "Thiết kế đồ họa",
                            University = "Đại học Mỹ thuật Công nghiệp"
                        },
                        new
                        {
                            UserId = 5,
                            Bio = "Chuyên viên làm slide slide PowerPoint, slide thuyết trình chuyên nghiệp, thuyết trình dự án tốt nghiệp.",
                            DateOfBirth = new DateTime(2004, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Lê Hải Đăng",
                            GPA = 3.5,
                            Gender = "Nam",
                            GraduationYear = 2026,
                            Major = "Kinh tế quốc tế",
                            University = "Đại học Ngoại Thương"
                        });
                });

            modelBuilder.Entity("JobForStudents.Models.StudentSkill", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceMonths")
                        .HasColumnType("integer");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("StudentSkills");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SkillId = 9,
                            ExperienceMonths = 12,
                            SkillLevel = "Intermediate"
                        },
                        new
                        {
                            StudentId = 1,
                            SkillId = 10,
                            ExperienceMonths = 6,
                            SkillLevel = "Beginner"
                        },
                        new
                        {
                            StudentId = 2,
                            SkillId = 2,
                            ExperienceMonths = 24,
                            SkillLevel = "Expert"
                        },
                        new
                        {
                            StudentId = 2,
                            SkillId = 1,
                            ExperienceMonths = 18,
                            SkillLevel = "Intermediate"
                        },
                        new
                        {
                            StudentId = 5,
                            SkillId = 5,
                            ExperienceMonths = 12,
                            SkillLevel = "Intermediate"
                        });
                });

            modelBuilder.Entity("JobForStudents.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("BankAccountName")
                        .HasColumnType("text");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("JobForStudents.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student1@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "0912345671",
                            Role = "Student",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student2@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "0912345672",
                            Role = "Student",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "business1@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "0912345673",
                            Role = "Business",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "business2@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "0912345674",
                            Role = "Business",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student3@gmail.com",
                            IsDeleted = false,
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "0912345675",
                            Role = "Student",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("JobForStudents.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 500000m,
                            UpdatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 1200000m,
                            UpdatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Balance = 25000000m,
                            UpdatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Balance = 10000000m,
                            UpdatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Balance = 0m,
                            UpdatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("JobForStudents.Models.BusinessProfile", b =>
                {
                    b.HasOne("JobForStudents.Models.User", "User")
                        .WithOne("BusinessProfile")
                        .HasForeignKey("JobForStudents.Models.BusinessProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobForStudents.Models.Certificate", b =>
                {
                    b.HasOne("JobForStudents.Models.StudentProfile", "StudentProfile")
                        .WithMany("Certificates")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("JobForStudents.Models.JobBid", b =>
                {
                    b.HasOne("JobForStudents.Models.JobPost", "JobPost")
                        .WithMany("JobBids")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobForStudents.Models.StudentProfile", "StudentProfile")
                        .WithMany("JobBids")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("JobForStudents.Models.JobContract", b =>
                {
                    b.HasOne("JobForStudents.Models.BusinessProfile", "BusinessProfile")
                        .WithMany("JobContracts")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobForStudents.Models.JobPost", "JobPost")
                        .WithMany("JobContracts")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobForStudents.Models.StudentProfile", "StudentProfile")
                        .WithMany("JobContracts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessProfile");

                    b.Navigation("JobPost");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("JobForStudents.Models.JobPost", b =>
                {
                    b.HasOne("JobForStudents.Models.BusinessProfile", "BusinessProfile")
                        .WithMany("JobPosts")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessProfile");
                });

            modelBuilder.Entity("JobForStudents.Models.JobPostSkill", b =>
                {
                    b.HasOne("JobForStudents.Models.JobPost", "JobPost")
                        .WithMany("JobPostSkills")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobForStudents.Models.Skill", "Skill")
                        .WithMany("JobPostSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("JobForStudents.Models.Message", b =>
                {
                    b.HasOne("JobForStudents.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobForStudents.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("JobForStudents.Models.Notification", b =>
                {
                    b.HasOne("JobForStudents.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobForStudents.Models.PortfolioProject", b =>
                {
                    b.HasOne("JobForStudents.Models.StudentProfile", "StudentProfile")
                        .WithMany("PortfolioProjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("JobForStudents.Models.Review", b =>
                {
                    b.HasOne("JobForStudents.Models.JobContract", "JobContract")
                        .WithMany("Reviews")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobForStudents.Models.Review", "ParentReview")
                        .WithMany("Replies")
                        .HasForeignKey("ParentReviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JobForStudents.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobContract");

                    b.Navigation("ParentReview");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("JobForStudents.Models.SavedJob", b =>
                {
                    b.HasOne("JobForStudents.Models.JobPost", "JobPost")
                        .WithMany("SavedJobs")
                        .HasForeignKey("JobPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobForStudents.Models.StudentProfile", "StudentProfile")
                        .WithMany("SavedJobs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPost");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("JobForStudents.Models.StudentProfile", b =>
                {
                    b.HasOne("JobForStudents.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("JobForStudents.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobForStudents.Models.StudentSkill", b =>
                {
                    b.HasOne("JobForStudents.Models.Skill", "Skill")
                        .WithMany("StudentSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobForStudents.Models.StudentProfile", "StudentProfile")
                        .WithMany("StudentSkills")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("JobForStudents.Models.Transaction", b =>
                {
                    b.HasOne("JobForStudents.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("JobForStudents.Models.Wallet", b =>
                {
                    b.HasOne("JobForStudents.Models.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("JobForStudents.Models.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobForStudents.Models.BusinessProfile", b =>
                {
                    b.Navigation("JobContracts");

                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("JobForStudents.Models.JobContract", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("JobForStudents.Models.JobPost", b =>
                {
                    b.Navigation("JobBids");

                    b.Navigation("JobContracts");

                    b.Navigation("JobPostSkills");

                    b.Navigation("SavedJobs");
                });

            modelBuilder.Entity("JobForStudents.Models.Review", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("JobForStudents.Models.Skill", b =>
                {
                    b.Navigation("JobPostSkills");

                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("JobForStudents.Models.StudentProfile", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("JobBids");

                    b.Navigation("JobContracts");

                    b.Navigation("PortfolioProjects");

                    b.Navigation("SavedJobs");

                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("JobForStudents.Models.User", b =>
                {
                    b.Navigation("BusinessProfile");

                    b.Navigation("Notifications");

                    b.Navigation("StudentProfile");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("JobForStudents.Models.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
